### ISSUE TITLE
Домашка №3 (ООП)

### ISSUE THREAD

**Issue by kottans-net** [kgnatovska/acsharpharpoon#4]
Предлагаем вам выполнить домашку по ООП https://github.com/Zaknafeyn/OOP.Task

**Comment by kgnatovska** [comment]
commited my solution to branch oop

**Comment by kottans-net** [comment]
Проверено.
Есть несколько замечаний:
В свойстве ShapeName можно вернуть имя фигуры литералом: public override string ShapeName
{ get { return "Shape Name"; } } или даже так: ShapeName => "Shape Name";

Хорошее решение - проверка параметра Multiplier на ноль. В более строгом варианте проверки можно было даже бросать исключение, но проверку нужно делать в одном месте - хорошее место для проверки - метод set свойства Multiplier. Хорошее решение могло бы выглядеть так:
 private byte _multiplier;
 public byte Multiplier { 
    get {return _multiplier}; 
    set{_multiplier = value == 0 ? 1 : _multiplier; }
 }

В условных операторах когда есть только 2 ветки условий и выход из метода в каждой ветке, не обязательно указывать else, достаточно сделать так: 
if (Multiplier!=0)
       {
           return 2_Math.PI__radius_Multiplier;
        }
        return 2_Math.PI*_radius;

Метод Move одинаковый для всех классов - его можно и нужно выносить в базовый класс - это одно из преимуществ ООП. 

В коде старайся избегать дублирования.
